import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent


@pytest.fixture
def data_dir() -> Path:
    return REPO_ROOT / "result_tmp"


@pytest.fixture
def data_dir_mini() -> Path:
    return REPO_ROOT / "result_tmp_mini"


@pytest.fixture
def fixtures_dir() -> Path:
    return Path(__file__).resolve().parent / "fixtures"


@pytest.fixture
def dvtbudget_coef_path(fixtures_dir: Path) -> Path:
    return fixtures_dir / "dvtbudget_coef.jsonc"


@pytest.fixture(scope="session")
def expanded_mini_dir(tmp_path_factory) -> Path:
    """A self-contained copy of result_tmp_mini with a ground-truth
    FBC_expanded.csv generated by the ORIGINAL expansion script
    (gomi/expand_FBC_measure.py), run verbatim against the copy.

    Tests validate the engine against this instead of files in result_tmp,
    which get swapped out as the user iterates on sample data.
    """
    root = tmp_path_factory.mktemp("expand")
    data_copy = root / "result_tmp"
    shutil.copytree(REPO_ROOT / "result_tmp_mini", data_copy)

    script_dir = root / "gomi"
    script_dir.mkdir()
    script_copy = script_dir / "expand_FBC_measure.py"
    shutil.copy(REPO_ROOT / "gomi" / "expand_FBC_measure.py", script_copy)

    subprocess.run([sys.executable, str(script_copy)], check=True, capture_output=True)
    assert (data_copy / "FBC_expanded.csv").exists()
    return data_copy
