import json
import math
import subprocess
import sys

import polars as pl
import pytest

from scorelib import io_jsonc
from scorelib.cli import compute_score_file, compute_score_part
from scorelib.dvtbudget import load_board_temperatures
from scorelib.expression import evaluate_expression


@pytest.fixture
def run_config(fixtures_dir):
    return io_jsonc.load_run_config(fixtures_dir / "config.jsonc")


@pytest.fixture
def dvt_inputs(dvtbudget_coef_path, data_dir_mini):
    return {
        "dvtbudget_coef": io_jsonc.load_dvtbudget_coef(dvtbudget_coef_path),
        "board_temperatures": load_board_temperatures(data_dir_mini / "initial_temperature.csv"),
    }


def _expected_fbc_part(expanded_mini_dir, wlgroup):
    """Independent (eager, step-by-step) recomputation of the
    FBC_A2B_upper1_rel score part defined in tests/fixtures/config.jsonc,
    using the ground-truth expansion generated by the original script.

    The part references the derived WLgroup axis, so the group column exists
    from load time onward: the denominator pre-aggregation and the relative
    pairing keep groups distinct (a cross-group denominator would instead be
    spelled by adding WLgroup itself to denominator_pre_aggregation).
    """
    df = pl.read_csv(expanded_mini_dir / "FBC_expanded.csv")
    cols = ["Board", "Chip", "Block", "WL", "STR", "State", "Read_Label", "Read_Override", "FBC"]
    df = df.select(cols).with_columns(pl.col("Read_Override").cast(pl.Boolean))

    def to_group(wl: int) -> str:
        for name, (lo, hi) in wlgroup.items():
            if lo <= wl <= hi:
                return name
        raise AssertionError(f"WL {wl} not covered")

    df = df.with_columns(pl.col("WL").map_elements(to_group, return_dtype=pl.Utf8).alias("grp"))

    num = df.filter(pl.col("Read_Override")).drop("Read_Override")
    den = df.filter(~pl.col("Read_Override")).drop("Read_Override")

    # denominator pre-aggregation: mean over WL, then mean over STR (grp stays a key)
    den = den.group_by(["Board", "Chip", "Block", "STR", "State", "Read_Label", "grp"]).agg(pl.col("FBC").mean())
    den = den.group_by(["Board", "Chip", "Block", "State", "Read_Label", "grp"]).agg(pl.col("FBC").mean())
    den = den.rename({"FBC": "denom"})

    rel = num.join(den, on=["Board", "Chip", "Block", "State", "Read_Label", "grp"], how="left")
    rel = rel.with_columns(((pl.col("FBC") + 1) / (pl.col("denom") + 1)).alias("FBC")).drop("denom")

    rel = rel.filter(pl.col("Read_Label") == "read_level_upper1").drop("Read_Label")
    rel = rel.filter(pl.col("State") == "A2B").drop("State")

    # WL mean within each WLgroup (derived axis), then max across groups
    rel = rel.drop("WL").group_by(["Board", "Chip", "Block", "STR", "grp"]).agg(pl.col("FBC").mean())
    rel = rel.group_by(["Board", "Chip", "Block", "STR"]).agg(pl.col("FBC").max())

    # STR: mean over subset {0, 1}
    rel = rel.filter(pl.col("STR").is_in([0, 1]))
    rel = rel.group_by(["Board", "Chip", "Block"]).agg(pl.col("FBC").mean())
    # Board mean, Chip mean, Block max
    rel = rel.group_by(["Chip", "Block"]).agg(pl.col("FBC").mean())
    rel = rel.group_by(["Block"]).agg(pl.col("FBC").mean())
    return rel["FBC"].max()


def test_fbc_part_matches_independent_recomputation(expanded_mini_dir, run_config):
    part = next(p for p in run_config.optimization.score_parts if p.name == "FBC_A2B_upper1_rel")
    actual = compute_score_part(expanded_mini_dir, part, group_defs=run_config.group_defs())
    expected = _expected_fbc_part(expanded_mini_dir, run_config.optimization.WLgroup)
    assert actual == pytest.approx(expected)


def test_group_axis_reduced_after_other_axes(expanded_mini_dir, run_config):
    """The user scenario that group_reduce could not express: WL mean inside
    each WLgroup first, then Board/Chip/Block/STR aggregation, and the
    WLgroup reduction (max) at the very end."""
    from scorelib.models import ScorePart

    wlgroup = run_config.optimization.WLgroup
    part = ScorePart.model_validate(
        {
            "name": "late_group",
            "type": "FBC",
            "order": ["Read_Label", "State", "Read_Override", "WL", "STR", "Board", "Chip", "Block", "WLgroup"],
            "aggregations": {
                "Read_Label": {"op": "filter", "value": "read_level_upper1"},
                "State": {"op": "filter", "value": "A2B"},
                "Read_Override": {"op": "filter", "value": True},
                "WL": {"op": "mean"},
                "STR": {"op": "mean"},
                "Board": {"op": "max"},
                "Chip": {"op": "mean"},
                "Block": {"op": "mean"},
                "WLgroup": {"op": "max"},
            },
        }
    )
    actual = compute_score_part(expanded_mini_dir, part, group_defs=run_config.group_defs())

    df = pl.read_csv(expanded_mini_dir / "FBC_expanded.csv")
    df = df.filter(
        (pl.col("Read_Label") == "read_level_upper1")
        & (pl.col("State") == "A2B")
        & pl.col("Read_Override").cast(pl.Boolean)
    )

    def to_group(wl: int) -> str:
        return next(n for n, (lo, hi) in wlgroup.items() if lo <= wl <= hi)

    df = df.with_columns(pl.col("WL").map_elements(to_group, return_dtype=pl.Utf8).alias("g"))
    df = df.group_by(["g", "STR", "Board", "Chip", "Block"]).agg(pl.col("FBC").mean())
    df = df.group_by(["g", "Board", "Chip", "Block"]).agg(pl.col("FBC").mean())
    df = df.group_by(["g", "Chip", "Block"]).agg(pl.col("FBC").max())
    df = df.group_by(["g", "Block"]).agg(pl.col("FBC").mean())
    df = df.group_by(["g"]).agg(pl.col("FBC").mean())
    assert actual == pytest.approx(df["FBC"].max())


def test_group_values_outside_ranges_rejected(data_dir_mini):
    """Data rows falling outside every range must not silently form a
    null-label group."""
    from scorelib.models import GroupDef, ScorePart

    part = ScorePart.model_validate(
        {"name": "p", "type": "FBC", "order": ["G"], "aggregations": {"G": {"op": "max"}}}
    )
    defs = {"G": GroupDef(axis="WL", groups={"g0": (0, 1)})}  # data has WL > 1
    with pytest.raises(ValueError, match="not covered by any group"):
        compute_score_part(data_dir_mini, part, group_defs=defs)


def test_group_def_name_clashing_with_source_axis_rejected(data_dir_mini, run_config):
    from scorelib.models import GroupDef, ScorePart

    part = ScorePart.model_validate(
        {"name": "p", "type": "FBC", "order": ["WL"], "aggregations": {"WL": {"op": "max"}}}
    )
    bad = {"WL": GroupDef(axis="WL", groups={"g": (0, 100)})}
    with pytest.raises(ValueError, match="same name as its source axis"):
        compute_score_part(data_dir_mini, part, group_defs=bad)


def test_dvtbudget_part_is_finite(data_dir_mini, run_config, dvt_inputs):
    part = next(p for p in run_config.optimization.score_parts if p.name == "dVtBudget_R2A")
    value = compute_score_part(
        data_dir_mini, part, group_defs=run_config.group_defs(),
        generation=run_config.Generation, **dvt_inputs,
    )
    assert math.isfinite(value)


def test_compute_score_file_returns_all_parts(data_dir_mini, run_config, dvt_inputs):
    result = compute_score_file(data_dir_mini, run_config, **dvt_inputs)
    assert set(result) == {"Score", "FBC_A2B_upper1_rel", "dVtBudget_R2A"}
    expected_score = evaluate_expression(
        run_config.optimization.expression,
        {k: v for k, v in result.items() if k != "Score"},
    )
    assert result["Score"] == pytest.approx(expected_score)


def test_custom_part_computes(data_dir_mini, fixtures_dir):
    from scorelib.models import RunConfig

    rc = RunConfig.model_validate(
        {
            "Generation": "B9LS",
            "optimization": {
                "score_parts": [
                    {"name": "fixed_value", "type": "custom"},
                    {"name": "shifted", "type": "custom",
                     "function": "mean_fbc_plus_offset", "params": {"offset": 10}},
                ],
                "expression": "fixed_value + shifted",
            },
        }
    )
    result = compute_score_file(
        data_dir_mini, rc, custom_parts_path=fixtures_dir / "custom_parts.py"
    )
    assert result["fixed_value"] == 42.0
    df = pl.read_csv(data_dir_mini / "FBC.csv")
    assert result["shifted"] == pytest.approx(float(df["FBC"].mean()) + 10)
    assert result["Score"] == pytest.approx(result["fixed_value"] + result["shifted"])


def test_custom_part_errors(data_dir_mini, fixtures_dir):
    from scorelib.cli import SharedComputeContext
    from scorelib.custom import (
        CustomContext, compute_custom_part, list_custom_functions, load_custom_module,
    )
    from scorelib.models import ScorePart

    module = load_custom_module(fixtures_dir / "custom_parts.py")
    assert list_custom_functions(module) == [
        "broken_returns_nan", "fixed_value", "mean_fbc_plus_offset",
    ]  # _private_helper and the pl import are excluded

    ctx = CustomContext(data_dir=data_dir_mini)
    with pytest.raises(ValueError, match="not found"):
        compute_custom_part(ScorePart(name="nope", type="custom"), module, ctx)
    with pytest.raises(ValueError, match="finite"):
        compute_custom_part(ScorePart(name="broken_returns_nan", type="custom"), module, ctx)
    with pytest.raises(ValueError, match="no custom"):
        compute_score_part(data_dir_mini, ScorePart(name="fixed_value", type="custom"))


def test_custom_fields_rejected_on_pipeline_parts():
    from scorelib.models import ScorePart

    with pytest.raises(Exception, match="only valid on type='custom'"):
        ScorePart.model_validate({"name": "p", "type": "FBC", "function": "f"})
    with pytest.raises(Exception, match="takes no order"):
        ScorePart.model_validate(
            {"name": "p", "type": "custom", "order": ["WL"],
             "aggregations": {"WL": {"op": "mean"}}}
        )


def test_cli_subprocess_end_to_end(data_dir_mini, fixtures_dir, dvtbudget_coef_path):
    cmd = [
        sys.executable, "-m", "scorelib.cli",
        "--config", str(fixtures_dir / "config.jsonc"),
        "--data-dir", str(data_dir_mini),
        "--dvtbudget-coef", str(dvtbudget_coef_path),
        "--initial-temperature", str(data_dir_mini / "initial_temperature.csv"),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    assert proc.returncode == 0, proc.stderr
    result = json.loads(proc.stdout)
    assert set(result) == {"Score", "FBC_A2B_upper1_rel", "dVtBudget_R2A"}
    assert all(isinstance(v, float) for v in result.values())
